# 9 에러 처리

-   회복 가능한 에러
-   회복 불가능한 에러

-   러스트에는 예외(exception)와 같은 개념이 없음

# 9.1 panic! 매크로를 이용한 회복 불가능한 에러 처리

```rust
fn main() {
    panic!("crash and burn");
}

```

# 9.1.1 panic! 역추척 사용하기

-   실행 결과에 있는 노트를 보면 RUST_BACKTRACE 환경 변수를 이용해 정확히 어떻게 에러가 발생했는지를 역추적할 수 있다는 점을 알려주고 있다.

# 9.2 Result 타입으로 에러 처리하기

```rust
enum Result<T,E> {
    Ok(T),
    Err(E),
}
```

-   T와 E는 제네릭 타입 매개변수다.
-   T는 작업이 성공한 경우 Ok 열것값 안에 포함될 값의 타입
-   E는 작업이 실패한 경우 Err 열것값 안에 포함될 값의 타입이다.
-   이 두 가지 제네릭 타입 매개변수 덕분에 표준 라이브러리에 선언된 Result 타입을 작업의 실행 결과에 따라 성공값이나 에러값을 리턴해야하는 어떠한 상황에서도 활용할 수 있다.

```rust
use std::fs::File;

fn main() {
    let f = File::open("Hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => {
            panic!("파일 열기 실패 : {:?}", error);
        }
    };
}

```

-   match 타입을 이용해 Result 타입을 처리하는 방법

### 9.2.1 match 표현식으로 여러 종류의 에러 처리하기

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("Hello.txt");
    let _f = match f {
        Ok(file) => file,
        Err(ref error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("파일을 생성하지 못했습니다.: {:?}", e),
            },
            other_error => panic!("파일을 열지 못했습니다: {:?}", other_error),
        },
    };
}
```

### 9.2.2 에러 발생 시 패닉을 발생하는 더 빠른 방법: unwrap 과 expect

```rust
use std::fs::File;

fn main() {
    let f = File::open("Hello.txt").expect("파일을 열 수 없습니다.");
}

```

## 9.3 패닉에 빠질 것인가? 말 것인가?

-   실패할 가능성이 있는 코드는 unwrap
-   정확한 오류 지점 파악이 필요할 경우 expect
-   코드가 결국은 잘못된 사앹가 될 상황이라면 패닉을 발생시키는 것도 나쁜 선택이 아니다.

## 요약

-   panic! 매크로는 프로그림이 제대로 처리할 수 없는 비정상적인 상태에 놓였다는 것을 알려주고 유효하지 않거나 잘못된 값을 계속 사용하지 못하도록 프로세스를 종료한다.

-   Result 열거자는 러스트의 타입 시스템을 이용해 작업이 실패할 수도 있음을 명시하고 실패한 경우 프로그램을 회복할 기회를 제공한다. 또한 Result 타입을 리턴해서 호출 코드가 작업이 성공한 경우와 실패한 경우를 모두 처리할 수 있도록 유도할 수도 있다.
